module.exports={
    _meta:{
        schema:{
            type:"object",
            properties:{
                qid:{
                    type:"string",
                    title:"Question Id"
                },
                q:{
                    title:"Questions",
                    type:"array",
                    items:{
                        type:"string",
                        maxLength:140
                    }
                },
                a:{
                    type:"string",
                    title:"Anwser",
                    maxLength:8000,
                },
                t:{
                    type:"string",
                    title:"Topic"
                },
                r:{
                    title:"Response card",
                    type:"object",
                    properties:{
                        title:{
                            type:"string",
                            title:"Card Title",
                            maxLength:1000
                        },
                        text:{
                            type:"string",
                            title:"Card Text",
                            maxLength:5000
                        },
                        url:{
                            type:"string",
                            title:"Card Image Url",
                            maxLength:2000
                        }
                    }
                },
                l:{
                    type:"string",
                    title:"Lambda Hook"
                }
            },
            required:["qid","q","a"]
        }
    },
    qid:{
        type:"keyword"
    },
    questions:{
        type:"nested",
        properties:{
            q:{
                type:"string",
                analyzer:"english"
            }
        }
    },
    a:{
        type:"text",
        analyzer:"english"
    },
    t:{
        type:'text',
        norms:false,
        analyzer:"whitespace" 
    },
    r:{
        enabled:false,
        properties:{
            url:{type:"keyword"},
            text:{type:"text"},
            title:{type:"text"}
        }
    },
    l:{
        enabled:false,
        type:"keyword"
    }
}
                
