module.exports={
    qid:{
        type:"keyword"
    },
    questions:{
        type:"nested",
        properties:{
            q:{
                type:"string",
                analyzer:"english"
            }
        }
    },
    a:{
        type:"text",
        analyzer:"english"
    },
    t:{
        type:'text',
        norms:false,
        analyzer:"whitespace" 
    },
    r:{properties:{
        url:{type:"keyword"},
        text:{type:"text"},
        title:{type:"text"}
    }},
    l:{
        properties:{
            Arn:{type:"keyword"}
        }
    }
}
                
